blank_issues_enabled: true
contact_links:
  - name: âœ‰ï¸ My contacts
    url: https://linktr.ee/BennyExtreme
    about: Open the list of all my contacts
  - name: ğŸ”— Main repository
    url: https://github.com/lydianlights/yet-another-factory-planner
    about: Open the main repository from Rane Fields (lydianlights)
